# Generated by Django 5.1 on 2024-10-03 04:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('student_id', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'book',
            },
        ),
        migrations.CreateModel(
            name='Textbook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_date', models.DateField()),
                ('book_name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('checking', models.BooleanField(default=False)),
                ('payment_date', models.DateField(null=True)),
                ('student_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='textbooks', to='textbook.student')),
            ],
        ),
    ]
